server:
  port: 80
spring:
  application:
    name: consumer-openfeign-order
  cloud:
    zookeeper:
      connect-string: 125.70.255.142:2181
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true