server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.77.82.43:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 120.77.82.43:8858 #配置Sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'


