server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    zookeeper:
      connect-string: 120.77.82.43:2181
    gateway:
      routes:
        - id: payment_routh     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-hystrix-payment         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/hystrix/ok/**        # 断言，路径相匹配的进行路由
